from pathlib import Path
import random
import json
import csv
import shutil
from faker import Faker
from reportlab.pdfgen import canvas
from openpyxl import Workbook
import msgspec
import os

from storage_server.app.security.crypto import encrypt_path
from storage_server.app.models import DownloadMaster__c

fake = Faker("ja_JP")

EXTS = ["txt", "csv", "pdf", "json", "xlsx"]

BASE = Path(os.path.dirname(__file__)).resolve()

ContentDocumentLink_dir = BASE / "objects" / "ContentDocumentLink"
ContentVersion_dir = BASE / "objects" / "ContentVersion"
ContentVersionData_DIR = BASE / "objects" / "ContentVersionData"
json_dir = BASE / "objects" / "DownloadMaster__c"
file_dir = BASE / "storage" / "files"


# ------------------------------------------------------------
# フォルダクリア（安全に削除 → 再作成）
# ------------------------------------------------------------
def clear_dir(path: Path):
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


clear_dir(json_dir)
clear_dir(file_dir)
clear_dir(ContentVersion_dir)
clear_dir(ContentVersionData_DIR)
clear_dir(ContentDocumentLink_dir)


# ------------------------------------------------------------
# 各ファイル生成関数
# ------------------------------------------------------------
def create_txt(path: Path):
    text = "\n".join(fake.sentences(nb=5))
    path.write_text(text, encoding="utf-8")


def create_csv(path: Path):
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "name", "email"])
        for _ in range(10):
            writer.writerow([fake.uuid4(), fake.name(), fake.email()])


def create_pdf(path: Path):
    c = canvas.Canvas(str(path))
    c.drawString(100, 800, "Sample PDF generated by Faker")
    for i in range(10):
        c.drawString(100, 780 - i * 20, fake.sentence())
    c.save()


def create_json(path: Path):
    data = {
        "id": fake.uuid4(),
        "name": fake.name(),
        "email": fake.email(),
        "address": fake.address(),
    }
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def create_xlsx(path: Path):
    wb = Workbook()
    ws = wb.active
    if ws:
        ws.append(["id", "name", "email"])
        for _ in range(10):
            ws.append([str(fake.uuid4()), fake.name(), fake.email()])
    wb.save(path)

GENERATORS = {
    "txt": create_txt,
    "csv": create_csv,
    "pdf": create_pdf,
    "json": create_json,
    "xlsx": create_xlsx,
}


# ------------------------------------------------------------
# メインループ：ファイル生成 + DownloadMaster__c JSON 生成
# ------------------------------------------------------------
for i in range(1, 12):
    ext = random.choice(EXTS)
    real_file_path = file_dir / f"file_{i}.{ext}"

    # 本物のファイルを生成
    GENERATORS[ext](real_file_path)

    # DownloadMaster__c JSON のパス
    json_path = json_dir / f"DM-{i}.json"

    dm_data = DownloadMaster__c(
        id=f"DM-{i}",
        filename=f"file_{i}.{ext}",
        filename_disp=f"File {i}.{ext}",
        encrypted_filepath=encrypt_path(str(real_file_path)),
        extension=ext,
        status="Pending",
    )

    json_path.write_text(
        msgspec.json.encode(dm_data).decode("utf-8"),
        encoding="utf-8"
    )

print("サンプルデータ生成完了！（フォルダクリア済み）")
